DROP DATABASE IF EXISTS `163music`;
CREATE DATABASE `163music` CHARACTER SET utf8;
USE `163music`;


-- 歌手表
CREATE TABLE `artist` (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `page` SMALLINT UNSIGNED NOT NULL
);

-- 歌曲表
CREATE TABLE `song` (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `comment_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `artist_id` INT UNSIGNED NOT NULL
);

-- 评论表
CREATE TABLE comment (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `liked_count` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `song_id` INT UNSIGNED NOT NULL
);

-- 用户表
CREATE TABLE user (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `nickname` VARCHAR(255) NOT NULL
);

-- 日志表
CREATE TABLE log (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `task_name` VARCHAR(50) NOT NULL,
  `arg` INT UNSIGNED NOT NULL UNIQUE KEY,
  `result` TINYINT UNSIGNED NOT NULL,
  `msg` TEXT,
  `crawl_date` DATETIME NOT NULL
);
